### ISSUE TITLE
ImagedObject Dbl-click produces IllegalArgumentException: Invalid number of points in LinearRing

### ISSUE THREAD

**Issue by tsviar** [Scripta-Qumranica-Electronica/ScrollEditor#66]
This issue is common to all A Imaged Objects for personal copies:

When in Imaged Object Tab and double clicking on any point in the Image area and surrounding area, these Exceptions are issued:

1) Uncaught (in promise) IllegalArgumentException: Invalid number of points in LinearRing (found 2 - must be 0 or >= 4)
...
2) jsts.min.js?8e19:7 Uncaught (in promise) IllegalArgumentException: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)

Exceptions full text:
===================

jsts.min.js?8e19:7 Uncaught (in promise) IllegalArgumentException: Invalid number of points in LinearRing (found 2 - must be 0 or >= 4)
    at ut.validateConstruction (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:61808)
    at ut.constructor_ (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:61230)
    at new ut (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:61115)
    at Ct.createLinearRing (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:80654)
    at Ct.createLinearRing (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:80547)
    at eval (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:85573)
    at Array.map (<anonymous>)
    at n (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:85563)
    at Yt.parseGeometry_ (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:86232)
    at Yt.parse (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:83002)
n @ jsts.min.js?8e19:7
s @ jsts.min.js?8e19:7
validateConstruction @ jsts.min.js?8e19:7
constructor_ @ jsts.min.js?8e19:7
ut @ jsts.min.js?8e19:7
**createLinearRing @ jsts.min.js?8e19:7
createLinearRing @ jsts.min.js?8e19:7**
eval @ jsts.min.js?8e19:7
n @ jsts.min.js?8e19:7
**parseGeometry_ @ jsts.min.js?8e19:7**
parse @ jsts.min.js?8e19:7
read @ jsts.min.js?8e19:7
read @ jsts.min.js?8e19:7
isLegal @ Polygons.ts?68a8:274
_callee$ @ boundary-drawer.vue?2256:261
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
**checkPolygon @ boundary-drawer.vue?2256:33
pointerUp @ boundary-drawer.vue?2256:213
pointerup @ boundary-drawer.vue?c954:18**
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917

jsts.min.js?8e19:7 Uncaught (in promise) IllegalArgumentException: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)
    at ut.validateConstruction (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:61808)
    at ut.constructor_ (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:61230)
    at new ut (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:61115)
    at Ct.createLinearRing (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:80654)
    at Ct.createLinearRing (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:80547)
    at eval (webpack-internal:///./node_modules/jsts/dist/jsts.min.js:7:85573)
    at Array.map (<anonymous>)

Relevant  code could be:
==========================

src\components\polygons\boundary-drawer.vue

private async checkPolygon() ...

private pointerUp($event: PointerEvent) ...

 private checkPolygonCloseness():  ...

![IllegalArgumentException Image DblClick](https://user-images.githubusercontent.com/16132723/104440395-f6ddfd00-559a-11eb-948a-206dc879174f.jpg)

**Comment by zmbq** [comment]
This actually happens with a single click, as well. For some reason jsts throws an exception if the polygon is too short.
